### PR TITLE
fix: defocus input on tap and drawer open

### LINKED ISSUE #5: [layout] input doesn't defocus
The "Send a message..." input doesn't defocus for some reason after the keyboard is closed. This causes the keyboard to pop up whenever the main page is navigated to, which is mildly annoying.

### PR DESCRIPTION
**Pull request by cswills**
closes #5 

changes:
1. add `onDrawerChanged:` and `onEndDrawerChanged:` to home screen `Scaffold` to defocus input on drawer open
2. add `onTap:` to `InkWell` to defocus input when messages are tapped
3. wrap home screen `Scaffold` with `GestureDetector` to defocus input when tapped in most other areas

### CODE REVIEW

File: lib/screens/home.dart [hunk 1]
```diff
@@ -163,173 +163,186 @@ class _HomeScreenState extends State<HomeScreen> with TickerProviderStateMixin {
...
-        color: Theme.of(context).primaryColor,
-        child: SafeArea(
-          child: Container(
-            color: Theme.of(context).scaffoldBackgroundColor,
-            child: Builder(builder: (context) {
-              final chatPanelFooter = Consumer<LayoutModel>(
-                builder: (context, layoutModel, child) {
-                  if (layoutModel.isInteractionLockable && layoutModel.locked) {
+    return GestureDetector(
+        onTap: () => FocusManager.instance.primaryFocus?.unfocus(),
```
Comment (kevmo314) [inline lib/screens/home.dart:167]: Does this break the emote keyboard or command bar?

**Review by kevmo314 — CHANGES_REQUESTED** [review]

**Comment by chungwwei** [comment]
Also happens when you click the people icon. 
maybe adding `FocusManager.instance.primaryFocus?.unfocus();` will fix that too?

https://github.com/muxable/rtchat/blob/main/lib/screens/home.dart#L212

**Comment by chungwwei** [comment]
Also happens when you click the people icon. 
maybe adding `FocusManager.instance.primaryFocus?.unfocus();` will fix that too?

https://github.com/muxable/rtchat/blob/main/lib/screens/home.dart#L212

**Comment by cswills** [comment]
> Also happens when you click the people icon. maybe adding `FocusManager.instance.primaryFocus?.unfocus();` will fix that too?
> 
> https://github.com/muxable/rtchat/blob/main/lib/screens/home.dart#L212

https://github.com/cswills/rtchat/blob/ae822cfae8e80b4bafda7c0285311e73b7b5d5eb/lib/screens/home.dart#L174-L175
This code defocuses input when the people icon is pressed.

File: lib/screens/home.dart (hunk 1 above)
Comment (kevmo314) [reply lib/screens/home.dart:167]: Oh I see, sounds good 👍

**Review by kevmo314 — APPROVED** [review]
