### PR TITLE
fix: switch stream preview when channel changes

### LINKED ISSUE #395: [preview] switching channels doesn't switch preview if it's open
If the stream preview is open it won't get switched when the channel changes.

### PR DESCRIPTION
**Pull request by cswills**
closes #395

### CODE REVIEW

File: lib/components/stream_preview.dart [hunk 1]
```diff
@@ -20,17 +20,24 @@ class StreamPreview extends StatefulWidget {
...
 
   var _isOverlayActive = false;
   Timer? _overlayTimer;
 
   @override
   Widget build(BuildContext context) {
+    final newUrl =
+        'https://player.twitch.tv/?channel=${widget.channelDisplayName}&controls=false&parent=chat.rtirl.com&muted=false';
+    if (url != newUrl && _controller != null) {
+      _controller!.loadUrl(newUrl);
```
Comment (kevmo314) [inline lib/components/stream_preview.dart:33]: `build()` shouldn't have side effects, can this go in https://api.flutter.dev/flutter/widgets/State/didUpdateWidget.html instead?

Comment (kevmo314) [reply lib/components/stream_preview.dart:34]: Nice, thanks!

**Review by kevmo314 — APPROVED** [review]
