### PR TITLE
fix: allow auth for account with no email

### LINKED ISSUE #317: can't login in the app

### PR DESCRIPTION
**Pull request by juaoose**
Fixes #317 

This is if we want to allow signup without email.

### CODE REVIEW

File: functions/src/auth.ts [hunk 1]
```diff
@@ -108,7 +108,7 @@ app.get("/auth/twitch/callback", async (req, res) => {
 
   // save the profile information too.
   const twitchProfile = {
-    email,
+    ...email ? email: {},
```
Comment (kevmo314) [inline functions/src/auth.ts:111]: Isn't email a string? Conditionally add the field?

**Review by kevmo314 — APPROVED** [review]
