### PR TITLE
fix: removed redundant pin switch for events

### LINKED ISSUE #226: [events] remove isEventPinnable
If `eventDuration` is zero, it's semantically the same as not being pinnable, right? So I think we can get rid of `isEventPinnable` and make the sliders go to zero?

### PR DESCRIPTION
**Pull request by chungwwei**
Closes #226

Pin switch is redundant, its functionality can be replaced by the slider.

I also changed the divisions on the sliders for events, so they all range [0, 30] with a step of 2.

### CODE REVIEW

File: lib/components/chat_panel.dart [hunk 1]
```diff
@@ -78,24 +78,24 @@ DateTime? _getExpiration(
     MessageModel model, EventSubConfigurationModel eventSubConfigurationModel) {
   if (model is TwitchRaidEventModel) {
     final raidEventConfig = eventSubConfigurationModel.raidEventConfig;
-    return raidEventConfig.isEventPinnable
+    return raidEventConfig.eventDuration.inSeconds > 0
```
Comment (kevmo314) [inline lib/components/chat_panel.dart:81]: `.eventDuration > Duration.zero` :)

**Review by juaoose — APPROVED** [review]
