### PR TITLE
fix: disable overlay when video is not playing, add loading overlay

### LINKED ISSUE #375: offline screen for stream preview

### PR DESCRIPTION
**Pull request by kevmo314**
Closes #375

### CODE REVIEW

File: lib/components/stream_preview.dart [hunk 1]
```diff
@@ -76,17 +76,17 @@ class _StreamPreviewState extends State<StreamPreview> {
               name: "Flutter",
               onMessageReceived: (message) {
                 final params = jsonDecode(message.message)["params"];
-                if (params != null) {
+                if (params is Map) {
                   setState(() => _playerState = params["playback"]);
```
Comment (juaoose) [inline lib/components/stream_preview.dart:80]: Not exactly from this PR, but it looks like this `setState((){})` will throw errors as it's sometimes called then the widget is not mounted. It does not seem to crash the app.

**Review by juaoose — APPROVED** [review]

File: lib/components/stream_preview.dart (hunk 1 above)
Comment (kevmo314) [reply lib/components/stream_preview.dart:80]: Oh good catch, I added some mounted guards to catch that.
